name: bottom_navigation_riverpod
description: Bottom navigation with multiple beamers, login guard, and navigation state managed by riverpod.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  beamer: ^1.5.5

  cupertino_icons: ^1.0.3
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.1.1
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
